name: screen_time_pro
description: A clean, professional screen time tracking app (Android).
version: 1.0.0+1
publish_to: 'none'


environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  fl_chart: ^0.69.1
  intl: ^0.18.1


flutter:
  uses-material-design: true