name: screen_time_pro
description: Professional minimal screen time analytics app (Android only)
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  usage_stats: ^1.3.1
  fl_chart: ^0.69.0
  http: ^1.1.0
  intl: ^0.18.1


# Note: verify latest versions on pub.dev before publishing


dev_dependencies:
  flutter_test:
    sdk: flutter